# This is a basic workflow to help you get started with Actions

name: Deploy Private ARO Cluster

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      aro_rg:
        description: The resource group to deploy the cluster to
        type: string
        required: true
        default: aro-private
      aro_cluster_name:
        description: The name of the cluster to deploy
        type: string
        required: true
        default: aroprivatefta
      aro_vnet_name:
        description: The name of the virtual network to deploy the cluster to
        type: string
        required: true
        default: aro-vnet
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-aro-prerrequisites:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      # # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3

      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.

      # Deploy ARO cluster
      - name: Deploy ARO
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az aro create \
            --resource-group "${{ github.event.inputs.aro_rg }}" \
            --name "${{ github.event.inputs.aro_cluster_name }}" \
            --vnet ${{ github.event.inputs.aro_vnet_name }}  \
            --master-subnet master \
            --worker-subnet worker \
            --apiserver-visibility Public \
            --ingress-visibility Public
